name: trilinka_mobile
description: TriLink School Management System - Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  go_router: ^14.8.1
  fl_chart: ^0.70.2
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
